import os
from pathlib import Path
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

# 1. Get the absolute path of the folder this current script lives in
CURRENT_DIR = Path(__file__).resolve().parent
DATABASE_FILE = CURRENT_DIR / "roadpulse.db"
# 2. Force create the folder if it doesn't exist

# 3. Build the absolute SQLite URL
DATABASE_URL = f"sqlite:///{DATABASE_FILE}"

# Note: On Windows, standard three slashes 'sqlite:///' works perfectly 
# with the absolute path generated by Pathlib.

engine = create_engine(
    DATABASE_URL, 
    connect_args={"check_same_thread": False}
)

SessionLocal = sessionmaker(
    autocommit=False, 
    autoflush=False, 
    bind=engine
)

Base = declarative_base()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()